'use client';

import React, { useState } from 'react';
import { Sparkles, FileText, CheckCircle2, Download, Layers, Loader2, ArrowRight, BookOpen, ShieldCheck, Copy, Check, FileDown } from 'lucide-react';
import { CitationPill } from './CitationPill';
import { CitationInspector, ActiveCitation } from './CitationInspector';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:8000';

interface ReportStudioViewProps {
  documents: Array<{ file_name: string }>;
}

export const ReportStudioView: React.FC<ReportStudioViewProps> = ({ documents }) => {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [currentStep, setCurrentStep] = useState<string>('');
  const [outline, setOutline] = useState<Array<{ title: string; description: string }>>([]);
  const [reportMarkdown, setReportMarkdown] = useState<string>('');
  const [citations, setCitations] = useState<Array<{ file_name: string; page_number: number }>>([]);
  const [copied, setCopied] = useState(false);
  const [activeCitation, setActiveCitation] = useState<ActiveCitation | null>(null);

  const samplePrompts = [
    "Draft a 4-page Policy Brief on Renewable Energy Incentives & Carbon Offsets",
    "Prepare an ESG Regulatory Compliance Assessment under EU CSRD",
    "Synthesize IPCC AR6 Climate Mitigation Benchmarks into an Executive Report"
  ];

  const handleGenerateReport = async (overridePrompt?: string) => {
    const activePrompt = overridePrompt || prompt;
    if (!activePrompt.trim() || loading) return;

    setLoading(true);
    setCurrentStep('OutlinePlanner: Structuring multi-section outline...');
    setReportMarkdown('');
    setOutline([]);

    try {
      const response = await fetch(`${API_BASE_URL}/api/reports/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: activePrompt,
          selected_docs: documents.map((d) => d.file_name)
        })
      });

      if (!response.ok) {
        throw new Error('Report generation failed');
      }

      const data = await response.json();
      setOutline(data.outline || []);
      setReportMarkdown(data.report_markdown || '');
      setCitations(data.citations || []);
      setCurrentStep('Completed');
    } catch (error) {
      setCurrentStep('Error encountered');
      setReportMarkdown('An error occurred during multi-agent report generation. Please verify backend logs and NVIDIA API key status.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Policy_Report_${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert("Please allow popups to export PDF.");
      return;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Sustainability Policy Analysis Report</title>
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 40px; color: #111; line-height: 1.6; }
            h1 { font-size: 24px; border-bottom: 2px solid #7c3aed; padding-bottom: 8px; margin-bottom: 16px; color: #1e1b4b; }
            h2 { font-size: 18px; color: #4338ca; margin-top: 24px; border-bottom: 1px solid #e0e7ff; padding-bottom: 4px; }
            p { font-size: 14px; text-align: justify; }
            .meta { font-size: 12px; color: #64748b; margin-bottom: 20px; font-style: italic; }
            .citation-tag { font-size: 11px; background: #e0e7ff; color: #4338ca; padding: 2px 6px; border-radius: 4px; font-weight: bold; }
            footer { margin-top: 40px; border-top: 1px solid #ccc; padding-top: 12px; font-size: 11px; color: #666; text-align: center; }
          </style>
        </head>
        <body>
          <h1>EcoResearch AI — Policy Briefing Report</h1>
          <div class="meta">Synthesized via Parallel LangGraph Multi-Agent Engine · Grounded with 100% Verified Citations</div>
          <div>${reportMarkdown.replace(/\n\n/g, '<br/><br/>').replace(/\[(?:Doc:\s*)?([^,\]]+),\s*p(?:age)?\.\s*(\d+)\]/g, '<span class="citation-tag">[$1, p. $2]</span>')}</div>
          <footer>Generated by EcoResearch AI Workspace</footer>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  const renderFormattedMarkdown = (text: string) => {
    const citationRegex = /\[(?:Doc:\s*)?([^,\]]+),\s*p(?:age)?\.\s*(\d+)\]/g;
    const parts = [];
    let lastIndex = 0;
    let match;

    while ((match = citationRegex.exec(text)) !== null) {
      if (match.index > lastIndex) {
        parts.push(text.substring(lastIndex, match.index));
      }

      const fileName = match[1].trim();
      const pageNumber = parseInt(match[2], 10);

      parts.push(
        <CitationPill
          key={match.index}
          fileName={fileName}
          pageNumber={pageNumber}
          onInspect={(cit) => setActiveCitation({
            fileName: cit.fileName,
            pageNumber: cit.pageNumber,
            verbatimSnippet: `Source snippet reference from ${cit.fileName}, page ${cit.pageNumber}.`
          })}
        />
      );

      lastIndex = citationRegex.lastIndex;
    }

    if (lastIndex < text.length) {
      parts.push(text.substring(lastIndex));
    }

    return parts.length > 0 ? parts : text;
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', position: 'relative' }}>
      {/* Header Banner */}
      <div className="ui-box" style={{ borderLeft: '4px solid #06b6d4', display: 'flex', alignItems: 'center', justify: 'space-between' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#38bdf8', fontSize: '13px', fontWeight: '700', textTransform: 'uppercase', marginBottom: '4px' }}>
            <Sparkles size={16} />
            <span>Parallel LangGraph Multi-Agent Report Studio</span>
          </div>
          <h1 style={{ fontSize: '24px', fontWeight: '700', color: '#fff', margin: 0 }} className="font-heading">
            Autonomous Policy Brief Synthesis (30-60s Parallel Generation)
          </h1>
          <p style={{ fontSize: '14px', color: '#94a3b8', marginTop: '4px' }}>
            Dispatch parallel LangGraph sub-agents (`OutlinePlanner` → `SectionResearcher` → `CitationVerifier` → `ReportSynthesizer`) to compile multi-page reports with 100% verifiable citations.
          </p>
        </div>

        <span className="badge-purple" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <ShieldCheck size={16} />
          <span>Citation Auditor Active</span>
        </span>
      </div>

      {/* Main Studio Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: '5fr 7fr', gap: '24px' }}>
        {/* Left Column: Form Controls */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          <div className="ui-box" style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <FileText size={20} style={{ color: '#a78bfa' }} />
              <h2 style={{ fontSize: '17px', fontWeight: '700', color: '#fff', margin: 0 }} className="font-heading">
                Report Objective & Prompt Builder
              </h2>
            </div>

            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={4}
              placeholder="Specify the scope of your policy brief (e.g. Generate a 4-page Policy Brief comparing renewable energy targets and carbon offset guidelines across our uploaded papers...)"
              className="form-textarea"
            />

            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <span style={{ fontSize: '12px', fontWeight: '700', color: '#64748b', textTransform: 'uppercase' }}>
                Sample Presets:
              </span>
              {samplePrompts.map((sp, idx) => (
                <button
                  key={idx}
                  onClick={() => {
                    setPrompt(sp);
                    handleGenerateReport(sp);
                  }}
                  className="btn-ghost-dark"
                  style={{ fontSize: '13px', textAlign: 'left', display: 'flex', alignItems: 'center', justify: 'space-between' }}
                >
                  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{sp}</span>
                  <ArrowRight size={14} style={{ opacity: 0.6 }} />
                </button>
              ))}
            </div>

            <button
              onClick={() => handleGenerateReport()}
              disabled={loading || !prompt.trim()}
              className="btn-violet"
              style={{ width: '100%', justifyContent: 'center', padding: '12px', opacity: loading || !prompt.trim() ? 0.5 : 1 }}
            >
              {loading ? <Loader2 size={18} className="animate-spin" /> : <Sparkles size={18} />}
              <span>{loading ? 'Executing Parallel Agents (30-60s)...' : 'Compile Policy Report'}</span>
            </button>
          </div>

          {/* LangGraph Agent Workflow Stepper */}
          {loading && (
            <div className="ui-box" style={{ borderLeft: '4px solid #7c3aed', display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#c4b5fd', fontSize: '14px', fontWeight: '600' }}>
                <Loader2 size={16} className="animate-spin" />
                <span>Parallel LangGraph Agent Execution</span>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', fontSize: '13px', fontFamily: 'monospace' }}>
                <div style={{ color: '#34d399', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <CheckCircle2 size={15} />
                  <span>1. OutlinePlanner (NVIDIA Llama 3.1)</span>
                </div>
                <div style={{ color: '#c4b5fd', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <Loader2 size={15} className="animate-spin" />
                  <span>2. Parallel Section Researchers (asyncio.gather)</span>
                </div>
                <div style={{ color: '#64748b', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <span style={{ width: '12px', height: '12px', borderRadius: '50%', border: '1px solid #64748b' }} />
                  <span>3. CitationVerifier (Strict 100% Audit)</span>
                </div>
                <div style={{ color: '#64748b', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <span style={{ width: '12px', height: '12px', borderRadius: '50%', border: '1px solid #64748b' }} />
                  <span>4. ReportSynthesizer (Markdown Assembly)</span>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Right Column: Live Markdown Report Preview */}
        <div>
          {!reportMarkdown ? (
            <div className="ui-box" style={{ textAlign: 'center', padding: '60px 20px', minHeight: '400px', display: 'flex', flexDirection: 'column', bg: 'rgba(15, 23, 42, 0.5)', border: '1px dashed rgba(255, 255, 255, 0.15)', alignItems: 'center', justify: 'center', gap: '12px' }}>
              <BookOpen size={40} style={{ color: '#64748b', opacity: 0.5 }} />
              <h3 style={{ fontSize: '18px', fontWeight: '700', color: '#fff', margin: 0 }} className="font-heading">Report Canvas Empty</h3>
              <p style={{ fontSize: '14px', color: '#64748b', maxWidth: '340px', margin: 0 }}>
                Enter your report prompt or choose a preset on the left to synthesize a policy brief in ~30-60 seconds.
              </p>
            </div>
          ) : (
            <div className="ui-box" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
              <div style={{ display: 'flex', alignItems: 'center', justify: 'space-between', paddingBottom: '12px', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <FileText size={20} style={{ color: '#38bdf8' }} />
                  <h2 style={{ fontSize: '18px', fontWeight: '700', color: '#fff', margin: 0 }} className="font-heading">Synthesized Policy Report</h2>
                </div>

                <div style={{ display: 'flex', gap: '8px' }}>
                  <button onClick={handleCopy} className="btn-ghost-dark" style={{ fontSize: '13px', padding: '7px 13px' }}>
                    {copied ? <Check size={15} style={{ color: '#34d399' }} /> : <Copy size={15} />}
                    <span>{copied ? 'Copied' : 'Copy'}</span>
                  </button>
                  <button onClick={handleDownloadMarkdown} className="btn-ghost-dark" style={{ fontSize: '13px', padding: '7px 13px' }}>
                    <FileDown size={15} />
                    <span>Download .md</span>
                  </button>
                  <button onClick={handleExportPDF} className="btn-violet" style={{ fontSize: '13px', padding: '7px 13px' }}>
                    <Download size={15} />
                    <span>Export PDF</span>
                  </button>
                </div>
              </div>

              <div style={{ fontSize: '15px', color: '#e2e8f0', lineHeight: '1.7', whiteSpace: 'pre-wrap' }}>
                {renderFormattedMarkdown(reportMarkdown)}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Slide-over Citation Inspector Drawer */}
      <CitationInspector
        activeCitation={activeCitation}
        onClose={() => setActiveCitation(null)}
      />
    </div>
  );
};
